version: "3.9"
services:
  go-postgresql-app:
    build: .
    networks:
      - db_network
    depends_on:
      - postgres
    ports:
      - "8080:80"
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db_network
volumes:
  postgres-vol:
networks:
  db_network:  